services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: focus-backend
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: focus-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always


