"""add admin_id to user

Revision ID: 296234587f46
Revises: 67d79005d5fb
Create Date: 2026-03-15 10:10:12.559155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296234587f46'
down_revision: Union[str, None] = '67d79005d5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'admin_id')
    # ### end Alembic commands ###
